#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v7
# autospec commit: f56f1fa
#
Name     : R-argparse
Version  : 2.2.3
Release  : 64
URL      : https://cran.r-project.org/src/contrib/argparse_2.2.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/argparse_2.2.3.tar.gz
Summary  : Command Line Optional and Positional Argument Parser
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-argparse-license = %{version}-%{release}
Requires: R-R6
Requires: R-findpython
Requires: R-jsonlite
BuildRequires : R-R6
BuildRequires : R-findpython
BuildRequires : R-jsonlite
BuildRequires : buildreq-R

%description
be used with 'Rscript' to write "#!" shebang scripts that gracefully
    accept positional and optional arguments and automatically generate usage.

%package license
Summary: license components for the R-argparse package.
Group: Default

%description license
license components for the R-argparse package.


%prep
%setup -q -n argparse
pushd ..
cp -a argparse buildavx2
popd
pushd ..
cp -a argparse buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712777572

%install
export SOURCE_DATE_EPOCH=1712777572
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-argparse
cp %{_builddir}/argparse/COPYING %{buildroot}/usr/share/package-licenses/R-argparse/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/argparse/COPYRIGHTS
/usr/lib64/R/library/argparse/DESCRIPTION
/usr/lib64/R/library/argparse/INDEX
/usr/lib64/R/library/argparse/Meta/Rd.rds
/usr/lib64/R/library/argparse/Meta/features.rds
/usr/lib64/R/library/argparse/Meta/hsearch.rds
/usr/lib64/R/library/argparse/Meta/links.rds
/usr/lib64/R/library/argparse/Meta/nsInfo.rds
/usr/lib64/R/library/argparse/Meta/package.rds
/usr/lib64/R/library/argparse/Meta/vignette.rds
/usr/lib64/R/library/argparse/NAMESPACE
/usr/lib64/R/library/argparse/NEWS.md
/usr/lib64/R/library/argparse/R/argparse
/usr/lib64/R/library/argparse/R/argparse.rdb
/usr/lib64/R/library/argparse/R/argparse.rdx
/usr/lib64/R/library/argparse/doc/argparse.R
/usr/lib64/R/library/argparse/doc/argparse.Rmd
/usr/lib64/R/library/argparse/doc/argparse.html
/usr/lib64/R/library/argparse/doc/index.html
/usr/lib64/R/library/argparse/exec/display_file.R
/usr/lib64/R/library/argparse/exec/example.R
/usr/lib64/R/library/argparse/help/AnIndex
/usr/lib64/R/library/argparse/help/aliases.rds
/usr/lib64/R/library/argparse/help/argparse.rdb
/usr/lib64/R/library/argparse/help/argparse.rdx
/usr/lib64/R/library/argparse/help/figures/logo.png
/usr/lib64/R/library/argparse/help/figures/logo.svg
/usr/lib64/R/library/argparse/help/paths.rds
/usr/lib64/R/library/argparse/html/00Index.html
/usr/lib64/R/library/argparse/html/R.css
/usr/lib64/R/library/argparse/tests/run-all.R
/usr/lib64/R/library/argparse/tests/testthat/scripts/test_help.R
/usr/lib64/R/library/argparse/tests/testthat/scripts/test_version.R
/usr/lib64/R/library/argparse/tests/testthat/test-argparse.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-argparse/b47456e2c1f38c40346ff00db976a2badf36b5e3
